sudo: false
language: scala
scala:
- 2.12.3
script:
- sbt ++$TRAVIS_SCALA_VERSION test
jdk:
- oraclejdk8
deploy:
  on:
    tags: true
after_success:
- if [ $TRAVIS_PULL_REQUEST = 'false' ]; then sbt ++$TRAVIS_SCALA_VERSION releaseEarly;
  fi
before_install:
- if [ $TRAVIS_PULL_REQUEST = 'false' ]; then openssl aes-256-cbc -K $encrypted_f717c0e11167_key
  -iv $encrypted_f717c0e11167_iv -in travis/secrets.tar.enc -out travis/secrets.tar
  -d; tar xv -C travis -f travis/secrets.tar; fi
env:
  global:
  - secure: FMSA2E05NQAQoJnQM3hzZqexh7NcI6oisoz4Vkuh3aTP9q+KosyuWh6NoVlMOWcteal0wGPlEmvTTxZ6/GUrYMH307f5XQ/TBIQL0zRzCeHC1AQF7zd71JfmLwe7/IeSJZsrsojMNyfjOZgujCeosP1syt0aohmyinDB+wXDopULQmd7efXK2Me17dyjqyio30G/bIdBm94g1UWSjfaCwNiz9jm/Zn/3xNFd2NYQBzBQVGxtUgzby1K7YtQ4icZuvgGfwcUHd7MJYS9O3x90yNLr/HnmWYtgNHhZfbjlnCr3WcC0f14M+moMIcVkuIrH0D8zpws35AycoJ8uWRDhGbki+KwoVtWQwBhuAxb56gkTeoJ3e3oZSaGEJJODUgyfiDQAFa372NwbzKvbYhTUK9fhe7UmQPdTWy4caVAAMTb/t6z0b6tTl4JQu4NJoOBCNf7xETL7LlAne0V55tezToriJOkbXeeXLGt+OINVW13x6cyfiiaWiEYA8XMPJFaiMw7vPIgQoeNdWTBPpTYaUxHqL+uI8XF3L6KgcD3evmENN+d4qUVCLuoiBexhkZI9HpUunpqM6pxM1Wzcb/mLpDwfjo8GT4QlCEEcCkaUQon6fkHol51Ygt8idOVIOSnwhxalLVeMtkNLCEEsIUn0wRH60iRIPdJm5mYrIS7z3xY=
  - secure: RDOJsI0w6CI81y++BJwplfyLH5c0pKUKzHAQEF5u3bW2N/7+/q0VJjNFZwAm3UyS/iYlfkFgEXpHcyGO0t0regh5l1yLSahSfy20sIw1e6GITUk9UFvAZO91nmyeAdJ9NfNIsqnHBAfNJW1doiyv+TGY3tn8+8EROYmspUxbbwTP+Wig8EUT2omhT3VND4csvhwstMZqUwaIfCCx9Fj0ExBAeij+lHj6vqbdxDZx40xZ9Y8k3ZS+ezjBDWwtKdbIQECQFd6iLbUctzzYfqj2ps96oaInZOkgNZ+uk0PTquMsQWc0rwzJuko5osrd3Tsljnl3VCozV49P6JsIIvAqdDXANCTEpsC1MBN7kd6ey9dtrHTJosLyTM/f0ZUZGP2Re8YEnLlpyQm4AAOHqBhGhhNU8eoJwNA/xEEdogLJXyzX/Rxb2ZFr5LAyHlxzdtbgLCmJRE4EvqIV8ZspXBE2jTCEuhKNt1oGch8xAaKAqPl/rTjD1ngF7t8kh83aQQb1vy+nDqoftbhChON/fiWjylrhR4An9iRDRqRKUjhgWlKr9gsd2XUqtjuGzeFZVwYGfr4QuQrLmNPPmoILUP7e0qfJK+eLZle+mx1edXC7qe3IwR9Ss+QaCKDBtztlQK16IPO/hzhXOrVcgb++xTZVYgZe3sBr4OHQGPNsOjoBnk0=
  - secure: Trnh+1oC3uWyYWI3IEc1LIDNKt6jJ2BH8N9Ga6sWoU3XOZxqs3sWtzuZo4O+9sVrJ6IW1rMzr9+T/s5tHUtMsc+Q6Cdgh1faOUkaSX+RRyIUzehd0aP5zu+S2K+gNHq5LlzM3cyCuRn5R5p9vc8tmdg0tFxkedfjRjRx/AfXbg52EWxwU04SETSyO0+ivhCTvIAsPzu77FMYgZryjPtJSzghq9v9RtahFpRQ4EEeSY68pU3aHWz5EimkWlKoUGwSV9q0QMbRQhU4rd0e0t/OkjDPQaHxdBEICFQh9Frls4WUIjYTpgVRwKx9qD12WS86Ux2Lv2oGpofI5PFXyxaOpHeG8x705vFWDqGYCLfatAT2M7iImxVrOegefNtSFkE5dIbrdZ40kNtcCWe+nlsQ0LhzFqYsNtI4haHYbq4QX1MBfBY2xKaKKWculEeGEdSpbZhR/fYKqhsYnt5rYxn+Dl372MsE6UN5kWs4O7Y9OLUdH8zu5QGc160XyZL6FjW4s95ndfPsaa+x4DukpxRoMPiRK1alp3CuKCk70PGkfO6xbEipe9F0Ev3eI4SoODbruWf9tZKVHYptufXYSMg55Kar+TXLwiZuwk/bTJz7l1BS+aQZXDtm8si1bsq/DYdALRPU6kBamcNRZ/EZZ3t2VuS4TQgH/ZkhWwTwgaXpEaU=
