sudo: false
language: scala
scala:
- 2.12.3
script:
- sbt ++$TRAVIS_SCALA_VERSION coverage test
jdk:
- oraclejdk8
deploy:
  on:
    tags: true
after_success:
- if [ $TRAVIS_PULL_REQUEST = 'false' ]; then sbt ++$TRAVIS_SCALA_VERSION releaseEarly;
  fi
env:
  global:
  - secure: TKaIHTEK6kZi2emEO+0MR4Yfr5FGLx4o2xuljPoD0XBBANnSEpnGhwq+dgyFgvl/EU6ZLp3x5MCOV+RR4odEGSSWHZlFaQiXtCOLq6aPxFfrvAlXXFijhhIy+6gppEIHKAsG45YnNn9JsY9Y2haYHsmarlWYKAPFfxXtzUHLSskoSI4ZLQ+vsuqSQju7OZwubIDZdeLaJgammuI/+u2pUbjJOfwRZkgtDOop5BtdWSXt9tq4DjXGcipgStiIADtipiatHfEWtCokLh6TNnuECXsjWSgkaBUft5ccMxpvqOiKghiVXPb4tUtIR5QeJTfn3TH0PCRG7mWtY2HVZNfjR3A7KH3LgoY0djmZDwy3Rk9KsdbbBxnkwi43yYcztkmqvJhvETTGorkygLdMXU1UKVMAkCUEpJLDQn0h1sw42/6EZJHv3vAOB5O/MBgQAKzi/GWhr9sCIv7EDAz2QGgvSmjWCZqIodT3v0CRjZuGQhKPweitJUWEGlRFzgWtJf73D9YrAtPnvtfEnO7+/INZqy/JCcQ8BBJVd0jSXCVdMNmjOkMBvnVEePQ1N6HiWp+xGKmv7bMIypIzvPiNi9rs2Fiojc7s7KIaUQuLlkdeI/pJshSnuUdnryHUvJxo92SEck1nfyf8ifQREZTBtUG12BrhRNprk6QSS4odXJcXUdc=
  - secure: DD0GFYSfd2OnDJFbPLoHeL2U1oJClV47uUG3N+BreSkDobsq7oCx/AFWTXRguLfeIydRMu4wSQPgZkWEdjATgKh4Sp4DM9lYoledo0Pr3EJ7yoZy2a4X83flp4VnoaiUYdCrq48Bg+95FNxPmC/GP64U4/+57aXcjZiWg9eD6X0A3YXyKTJDBEyxi8150+iMKajAkmhtIBeuRufhmYoVoS7NwATg4N+mJ/7NRShYXpZxiwyPRvbEXoOK4OaIZSq5u40zUM3zSbxrAhBF86lPn3eemAPlf7ZbaNgwLYHzjQ6nsncxZcREMMWJkQH8/gF7oXjuBopbGw36TOEFHqdTZFYcQRWN6BDM0T0meD6D9mknEfvptPXsOjCgNDqMxmwr/XK58Qy/nEndgpB4jq46uEITF3/XvItJaomPXGNLGeBgo9aVI9TC6dnJWaJOAQQWZwdDs78SWDJBJoEt7nNRrWq+VT8EO5wSapIGOPykr+yekHPzMZXY3bqO5abcJVt5oc8YtAB8rZEDpQ2qAG+JbjejLbKcnKbTA6RPI/kaBKd/MlCWvLwVAr5W/rVoD/gtQyxxpQIMVkupvKpcrNDReOU4qYdEcwdraDk2kNhuJ+1rTuMcmqL7vZEZbZ3e3bgTdyvnx1Ca6SqEYco0pSDqR9UtQRsSJXE/cQhQ+5G0qVk=
  - secure: Qv50RcSXHSyJLODpasDxrH6YJHpkV2s7ZTQm877ZBSO0z30At3nwg4Ul4Kt6eaRW+fqZxkdO//Q/q6Pfn8NKeEw1+kHLe9MaXadeZ+KljDCKpd/LiUOKfrWzHy5XnhZzqir3OLOpU/smBBjEMoMt/oFaNdIqUuQta1SlJCoSOovVQHpkZS/rwQEDsKadhBEWhBOLR/yUmophT4FyoksR9V8t23gqPNcKfka24ztxxgzvHdtcKZ9dkxnr+F1RmN0bjruajG/2MgF72zTnlqzveLBJ69COYx1iBvaCS+hwoaF9dXkOc17JQlAd585193W7k4o7oOLTRMZRLXuXRtD/FHZAyFnZ/dhjjEhcG9G4DAAMNZx7NvRtXuoHA9y349T+bC2aPTaTnrfoZwM1OB01SaW2BjCNC/w70C7a2+ONBZi4VWnipMsh6BbIrluoN8Gf2xIOvK4R9tOBRlThppQrAaYhxsExovTJibX20JuzEFwbD1QYoEtLl7sLydaNkFTtEEsKvYCutZb8FSRrr+1YVAePesrten2/oqM4l0eANEVCBNkCwXMT5j5AeNU0OwND4tDRjDW8odX8PM8kXPhZM1ddZCBddDcDMxVDMhJeOgQGXilfLRfNEIa13waCpE/EQMhcFkBPG6ZCvqfCrKqZrAL//iGpBO3n8hnOfy88Xog=
before_install:
- if [ $TRAVIS_PULL_REQUEST = 'false' ]; then openssl aes-256-cbc -K $encrypted_f717c0e11167_key 
  -iv $encrypted_f717c0e11167_iv -in travis/secrets.tar.enc -out travis/secrets.tar
  -d; tar xv -C travis -f travis/secrets.tar; fi
